// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rprwtwxfwixcgjoppheq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcnd0d3hmd2l4Y2dqb3BwaGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTU2NjEsImV4cCI6MjA2ODc5MTY2MX0.jF8UQlunqKwUvdT3HpglO6gQeWNRlIJ1_jr_yxx6NVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});